[package]
name = "rust-wirefish"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
pnet = "0.35.0"
serde = {version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
